<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PhabricatorPoniverseAuthProvider' => 'auth/PhabricatorPoniverseAuthProvider.php',
    'PhutilPoniverseAuthAdapter' => 'auth/PhutilPoniverseAuthAdapter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PhabricatorPoniverseAuthProvider' => 'PhabricatorOAuth2AuthProvider',
    'PhutilPoniverseAuthAdapter' => 'PhutilOAuthAuthAdapter',
  ),
));
